sudo: required

services:
  - docker

before_install:
  - docker build -t narcisse/docker-tutorial -f Dockerfile.dev .

script:
  - docker run -e CI=true narcisse/docker-tutorial npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "devops-tutorial"
  env: "DevopsTutorial-env"
  bucket_name: "elasticbeanstalk-us-east-2-199208108721"
  bucket_path: "devops-tutorial"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
